Uvítací zpráva do DM
Inkluzitron/Inkluzitron pull request #131
Opened 2021-07-04 23:30 UTC by janch32

Aby těch PRs nebylo málo, tak tady je další, Uvítací zpráva do DM.

2021-07-05 08:42 UTC, Khubajsn commented on src/Inkluzitron/Handlers/InviteHandler.cs
> +                    Config.GetValue<string>("Welcoming:Message"),
null check pls

2021-07-05 14:58 UTC, Khubajsn approved these changes

2021-07-06 08:33 UTC, Misha12 requested changes

2021-07-06 08:33 UTC, Misha12 commented on src/Inkluzitron/Handlers/InviteHandler.cs
> +            catch (HttpException)
```suggestion
            catch (HttpException ex) when (ex.DiscordCode == 50007)
```
Zase br br nezabíjel bych úplně všechny.

2021-07-06 10:38 UTC, Misha12 approved these changes

2021-07-06 10:38 UTC, merged