Skrytí duchů z tabulek a grafů (also emote fix)
Inkluzitron/Inkluzitron pull request #160
Opened 2022-11-21 21:36 UTC by janchaloupka

* Oprava emotů. Thanks Alpatron
 * Odstranění duchů z tabulky bodů, grafu bodů a bdsm modulu

2022-11-21 21:40 UTC, Khubajsn commented on src/Inkluzitron/Services/PointsService.cs
> +            // Fill the board with users but filter out all ghosts (people who are no loger on a server)
no longer

2022-11-21 21:40 UTC, Khubajsn commented on src/Inkluzitron/Services/PointsService.cs
> +                // Stop condition, we have iterated through the etire board
entire

2022-11-21 21:46 UTC, Khubajsn approved these changes

2022-11-22 07:25 UTC, Misha12 requested changes

2022-11-22 07:25 UTC, Misha12 commented on src/Inkluzitron/Services/GraphPaintingService.cs
> +                toplistResults[k] = toplistResults[k].Where(item => item.UserDisplayName != null).ToList().AsReadOnly();
Use `string.IsNullOrEmpty` instead.

2022-11-22 07:25 UTC, Misha12 commented on src/Inkluzitron/Services/PointsService.cs
> +                board.AddRange(boardWithGhosts.Where(p => p.UserDisplayName != null));
Use string.IsNullOrEmpty instead.

2022-11-22 16:01 UTC, janchaloupka commented on src/Inkluzitron/Services/GraphPaintingService.cs
> +                toplistResults[k] = toplistResults[k].Where(item => item.UserDisplayName != null).ToList().AsReadOnly();
Týjo, to si nemyslím. Sice nevím jestli jde nastavit prázdný username, ale to že uživatel není na serveru značí null a ne prázdný string.

2022-11-22 16:08 UTC, Misha12 approved these changes

2022-11-22 16:16 UTC, merged